CREATE TABLE DESIGNATIONS2023 (
  `ID` int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `DAY` int(2) DEFAULT NULL,
  `WEEK` int(2) DEFAULT NULL,
  `P_IN_WEEK` int(1) DEFAULT NULL,
  `MONTH` int(1) DEFAULT NULL,
  `PLACE` varchar(50) DEFAULT NULL,
  `TIME` char(8) DEFAULT NULL,
  `DESIGNATED_1` varchar(20) DEFAULT NULL,
  `DESIGNATED_2` varchar(20) DEFAULT NULL
);

CREATE TABLE `cart_places` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `PLACE` varchar(30) DEFAULT NULL,
  `STREET` varchar(30) DEFAULT NULL,
  `STREET_NUMBER` int(11) DEFAULT NULL,
  `DESCRIPTION` varchar(200) DEFAULT NULL,
  `GOOGLEMAPS_LINK` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`ID`)
);

CREATE TABLE `territories` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NUMBER` char(2) DEFAULT NULL,
  `LOCALIZATION` varchar(20) DEFAULT NULL,
  `STATUS` varchar(20) DEFAULT NULL,
  `LAST_WORK` int(6) DEFAULT NULL,
  `STREETS` varchar(1000) DEFAULT NULL,
  PRIMARY KEY (`ID`)
);

CREATE TABLE `territories_streets` (
  ID INT(11) NOT NULL AUTO_INCREMENT,
  STREET VARCHAR(30),
  STREET_LINK VARCHAR(100)
);
